# Sample Prometheus configuration
global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout: is set to the global default (10s).

#Local Prometheus server configuration
scrape_configs:
  - job_name: 'prometheus server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9091']

scrape_configs:
  - job_name: 'actuator-prometheus scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9001']
